yolo_model:

  config_file:
    name: yolov3-tiny_4classes.cfg
  weight_file:
    name: yolov3-tiny.backup
  threshold:
    value: 0.3
  detection_classes:
    names:
      - bicycle
      - aeroplane
      - boat
      - bottle